# Generated by Django 4.2 on 2024-10-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_remove_area_titular_subarea_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tipo_de_solicitud', models.SmallIntegerField(choices=[(1, 'Correo electrónico'), (2, 'Diseño gráfico impreso'), (3, 'Diseño gráfico web'), (4, 'Invitación a un evento'), (5, 'Publicación web'), (6, 'Soporte técnico'), (7, 'Solicitud de transparencia'), (8, 'Otros')], default=1)),
                ('asunto', models.CharField(default='', max_length=250)),
                ('descripcion', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('area_administrativa_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_area_admin_solicitante', to='Home.area')),
                ('unidad_administrativa_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_ua_solicitante', to='Home.unidadadministrativa')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_usuario_responsable', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_usuario_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['fecha', 'asunto'],
            },
        ),
        migrations.CreateModel(
            name='Ticket_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('respuesta', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_respuesta_ticket', to='Servicios.ticket')),
                ('usuario_respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_usuario_respuesta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket_Respuesta',
                'verbose_name_plural': 'Respuesta a los Tickets',
                'ordering': ['fecha', 'respuesta'],
            },
        ),
        migrations.CreateModel(
            name='Ticket_Respuesta_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('descripcion_imagen', models.CharField(default='', max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tickets/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/')),
                ('imagen_root', models.CharField(default='', max_length=250)),
                ('imagen_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_respuesta_ticket_id_01', to='Servicios.ticket')),
                ('ticket_respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_respuesta_id', to='Servicios.ticket_respuesta')),
                ('usuario_respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_usuario_respuesta_imagen_02', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket_Respuesta_Imagen',
                'verbose_name_plural': 'Imagenes de Respuesta a los Tickets',
                'ordering': ['fecha', 'descripcion_imagen'],
            },
        ),
        migrations.CreateModel(
            name='Ticket_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('descripcion_imagen', models.CharField(default='', max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tickets/<django.db.models.fields.related.ForeignKey>/')),
                ('imagen_root', models.CharField(default='', max_length=250)),
                ('imagen_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_imagen_ticket', to='Servicios.ticket')),
                ('usuario_respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_usuario_respuesta_01', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket_Respuesta',
                'verbose_name_plural': 'Respuesta a los Tickets',
                'ordering': ['fecha', 'descripcion_imagen'],
            },
        ),
    ]
