# Generated by Django 4.2 on 2024-10-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_imagen',
            name='imagen_root',
        ),
        migrations.RemoveField(
            model_name='ticket_respuesta_imagen',
            name='imagen_root',
        ),
        migrations.AlterField(
            model_name='ticket_imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/{ticket_id}'),
        ),
        migrations.AlterField(
            model_name='ticket_respuesta_imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/{id}/{ticket_id}/'),
        ),
    ]
