# Generated by Django 4.2 on 2024-10-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_alter_ticket_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_imagen',
            options={'ordering': ['fecha', 'descripcion_imagen'], 'verbose_name': 'Ticket_Respuesta', 'verbose_name_plural': 'Imagenes de los Tickets'},
        ),
    ]
