# Generated by Django 4.2 on 2024-10-10 23:50

import Servicios.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_ticket_imagen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_respuesta',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'Recibido'), (2, 'En proceso'), (3, 'En espera de aprobación'), (4, 'En espera de meterial/refacciones'), (5, 'En garantía'), (6, 'Terminado')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket_imagen',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=Servicios.functions.upload_path_handler_one, validators=[Servicios.functions.validate_file_extension, Servicios.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='ticket_respuesta_imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Servicios.functions.upload_path_handler_two, validators=[Servicios.functions.validate_file_extension, Servicios.functions.file_size]),
        ),
    ]
