# Generated by Django 5.0.7 on 2024-07-18 23:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=250)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_modi_por', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_titular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c030', models.IntegerField(default=0)),
                ('equipo', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=250)),
                ('procesador', models.CharField(max_length=250)),
                ('generacion', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=250)),
                ('discoduro', models.CharField(max_length=250)),
                ('tipodiscoduro', models.SmallIntegerField(blank=True, choices=[(1, 'HDD'), (2, 'SSD')], default=1, null=True)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('inventariomonitor', models.CharField(blank=True, max_length=30, null=True)),
                ('inventariomouse', models.CharField(blank=True, max_length=30, null=True)),
                ('inventarioteclado', models.CharField(blank=True, max_length=30, null=True)),
                ('conexion', models.CharField(blank=True, max_length=100, null=True)),
                ('tiponodo', models.CharField(blank=True, max_length=100, null=True)),
                ('anchobanda', models.CharField(blank=True, max_length=100, null=True)),
                ('numerotelefonico', models.CharField(blank=True, max_length=100, null=True)),
                ('garantia', models.CharField(blank=True, max_length=100, null=True)),
                ('antivirus', models.CharField(blank=True, max_length=250, null=True)),
                ('ofimatica', models.CharField(blank=True, max_length=250, null=True)),
                ('sistemaoperativo', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modidificado_el', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_area', to='Home.area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_creado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('usuarioresguardo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_usuarioresguardo', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.marca')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['unidadadministrativa', 'area'],
            },
        ),
        migrations.CreateModel(
            name='Area_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.area')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.equipo')),
            ],
            options={
                'verbose_name': 'Area_Equipo',
                'verbose_name_plural': 'Area_Equipos',
                'ordering': ['area', 'equipo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=250)),
                ('abreviatura', models.CharField(max_length=25)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidadadministrativa_modi_por', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidadadministrativa_titular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UnidadAdministrativa',
                'verbose_name_plural': 'UnidadesAdministrativas',
                'ordering': ['unidad'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='unidadadministrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_unidadadministrativa', to='Home.unidadadministrativa'),
        ),
        migrations.AddField(
            model_name='area',
            name='unidadadministrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.unidadadministrativa'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['serie'], name='Home_equipo_serie_1a758b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventario'], name='Home_equipo_inventa_9c9ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventariomonitor'], name='Home_equipo_inventa_5452fe_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventariomouse'], name='Home_equipo_inventa_ff8e90_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventarioteclado'], name='Home_equipo_inventa_0126c3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['tipodiscoduro'], name='Home_equipo_tipodis_64869d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['marca'], name='Home_equipo_marca_i_782a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['area'], name='Home_equipo_area_id_d7724c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['usuarioresguardo'], name='Home_equipo_usuario_561d61_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('serie', 'inventario'), name='home_equipo_unique'),
        ),
    ]
