# Generated by Django 5.1.1 on 2024-09-26 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('celulares', models.CharField(blank=True, max_length=250, null=True)),
                ('emails', models.CharField(blank=True, max_length=500, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['ap_paterno', 'ap_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(db_index=True, max_length=100, unique=True)),
                ('fabricante', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_modi_por', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_titular', to='Home.empleado')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c030', models.IntegerField(default=0)),
                ('equipo', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=250)),
                ('procesador', models.CharField(blank=True, max_length=250, null=True)),
                ('generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=250, null=True)),
                ('discoduro', models.CharField(blank=True, max_length=250, null=True)),
                ('tipodiscoduro', models.SmallIntegerField(blank=True, choices=[(1, 'HDD'), (2, 'SSD')], default=1, null=True)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('inventariomonitor', models.CharField(blank=True, max_length=30, null=True)),
                ('inventariomouse', models.CharField(blank=True, max_length=30, null=True)),
                ('inventarioteclado', models.CharField(blank=True, max_length=30, null=True)),
                ('conexion', models.CharField(blank=True, max_length=100, null=True)),
                ('tiponodo', models.CharField(blank=True, max_length=100, null=True)),
                ('anchobanda', models.CharField(blank=True, max_length=100, null=True)),
                ('numerotelefonico', models.CharField(blank=True, max_length=100, null=True)),
                ('garantia', models.CharField(blank=True, max_length=100, null=True)),
                ('antivirus', models.CharField(blank=True, max_length=250, null=True)),
                ('ofimatica', models.CharField(blank=True, max_length=250, null=True)),
                ('sistemaoperativo', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modidificado_el', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_creado_por', to=settings.AUTH_USER_MODEL)),
                ('empleadoresguardo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_empleadoresguardo', to='Home.empleado')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_marca', to='Home.marca')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['equipo'],
            },
        ),
        migrations.CreateModel(
            name='Area_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.area')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.equipo')),
            ],
            options={
                'verbose_name': 'Area_Equipo',
                'verbose_name_plural': 'Area_Equipos',
                'ordering': ['area', 'equipo'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_paterno', models.CharField(blank=True, max_length=150, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(blank=True, max_length=150, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('curp', models.CharField(blank=True, help_text='Se refiere a la CURP aplicada en México', max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, help_text='Se refiere al RFC aplicada por el SAT en México', max_length=13, verbose_name='RFC')),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento')),
                ('domicilio', models.TextField(blank=True, verbose_name='Domicilio')),
                ('genero', models.SmallIntegerField(blank=True, choices=[(1, 'Masculino'), (0, 'Femenino')], default=1, null=True)),
                ('session', models.CharField(blank=True, max_length=250, null=True)),
                ('estatus', models.SmallIntegerField(blank=True, choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('avatar_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('facebook', models.CharField(blank=True, max_length=150, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=150, verbose_name='X')),
                ('linkedin', models.CharField(blank=True, max_length=150, verbose_name='LinkedIn')),
                ('instagram', models.CharField(blank=True, max_length=150, verbose_name='Instagram')),
                ('github', models.CharField(blank=True, max_length=150, verbose_name='GitHub')),
                ('post', models.IntegerField(default=0, help_text='Elementos posteados', verbose_name='Post')),
                ('follower', models.IntegerField(default=0, help_text='Segudores', verbose_name='Followers')),
                ('folllowin', models.IntegerField(default=0, help_text='Siguendo', verbose_name='Followin')),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('modidificado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(db_index=True, max_length=250, unique=True)),
                ('abreviatura', models.CharField(db_index=True, max_length=25, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidadadministrativa_modi_por', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidadadministrativa_titular', to='Home.empleado')),
            ],
            options={
                'verbose_name': 'UnidadAdministrativa',
                'verbose_name_plural': 'UnidadesAdministrativas',
                'ordering': ['unidad'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='unidadadministrativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_ua', to='Home.unidadadministrativa'),
        ),
        migrations.AddField(
            model_name='area',
            name='unidadadministrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.unidadadministrativa'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['c030'], name='Home_equipo_c030_4a55d2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['serie'], name='Home_equipo_serie_1a758b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventario'], name='Home_equipo_inventa_9c9ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventariomonitor'], name='Home_equipo_inventa_5452fe_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventariomouse'], name='Home_equipo_inventa_ff8e90_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['inventarioteclado'], name='Home_equipo_inventa_0126c3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['tipodiscoduro'], name='Home_equipo_tipodis_64869d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['marca'], name='Home_equipo_marca_i_782a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['empleadoresguardo'], name='Home_equipo_emplead_5754a2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['unidadadministrativa'], name='Home_equipo_unidada_4a1ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('serie', 'inventario'), name='home_equipo_unique'),
        ),
    ]
