# Generated by Django 4.2 on 2024-10-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='titular',
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subarea', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.area')),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subarea_modi_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subarea',
                'verbose_name_plural': 'Subareas',
                'ordering': ['subarea'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelo_de_equipos_modi_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Fuente_de_financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_de_financiamiento', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuente_de_financiamiento_de_equipos_modi_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuente de financiamiento',
                'verbose_name_plural': 'Fuente de financiamientos',
                'ordering': ['fuente_de_financiamiento'],
            },
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condicion_de_equipos_modi_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condicion',
                'verbose_name_plural': 'Condiciones',
                'ordering': ['condicion'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_de_equipos_modi_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_de_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, max_length=250, unique=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_de_equipos_modi_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de equipo',
                'verbose_name_plural': 'Categoria de equipos',
                'ordering': ['categoria'],
            },
        ),
    ]
