# Generated by Django 5.0.7 on 2024-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_empleado_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadadministrativa',
            name='abreviatura',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadadministrativa',
            name='unidad',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
