# Generated by Django 5.0.7 on 2024-07-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_area_area_alter_marca_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
