# Generated by Django 4.2 on 2024-10-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_unidadadministrativa_options_alter_area_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadadministrativa',
            name='abreviatura',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadadministrativa',
            name='unidad',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
