# Generated by Django 4.2 on 2024-10-11 20:52

import Servicios.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_unidadadministrativa_abreviatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unidad_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_unidad_administrativa', to='Home.unidadadministrativa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[Servicios.functions.validate_file_extension, Servicios.functions.file_size]),
        ),
    ]
