# Generated by Django 5.0.7 on 2024-08-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_equipo_options_alter_equipo_discoduro_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipo',
            name='Home_equipo_area_id_d7724c_idx',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='area',
        ),
    ]
