# Generated by Django 4.2 on 2024-10-11 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_profile_unidad_administrativa_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadadministrativa',
            name='titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidadadministrativa_titular', to=settings.AUTH_USER_MODEL),
        ),
    ]
