# Generated by Django 5.0.7 on 2024-08-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_equipo_home_equipo_area_id_d7724c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='empleadoresguardo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_empleadoresguardo', to='Home.empleado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_marca', to='Home.marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='unidadadministrativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_ua', to='Home.unidadadministrativa'),
        ),
    ]
