# Generated by Django 4.1 on 2024-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_equipo_empleadoresguardo_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['unidadadministrativa'], name='Home_equipo_unidada_4a1ef5_idx'),
        ),
    ]
